### ISSUE TITLE
Weird and random uncaught error

### ISSUE THREAD

**Issue by stevapple** [Pierre-Lannoy/wp-keys-master#1]
**Describe the bug**
The plugin throws an uncaught error randomly. Since this is not observed in the frontend (only found in server logs), I suppose it is only triggered by cron or AJAX.

**To Reproduce**
Wait for it happens😂

**Expected behavior**
Error-free is best:)

**Screenshots**
```
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function get_privileges_for_user() on null in /var/www/blog/wp-content/plugins/keys-master/includes/system/class-password.php:463
Stack trace:
#0 /var/www/blog/wp-content/plugins/keys-master/includes/features/class-zookeeper.php(94): KeysMaster\System\Password::auto_revoke_password()
#1 /var/www/blog/wp-content/plugins/keys-master/includes/features/class-zookeeper.php(59): KeysMaster\Plugin\Feature\ZooKeeper::revoke_old_passwords()
#2 /var/www/blog/wp-includes/class-wp-hook.php(308): KeysMaster\Plugin\Feature\ZooKeeper::execute_tasks()
#3 /var/www/blog/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /var/www/blog/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /var/www/blog/wp-includes/load.php(1144): do_action()
#6 [internal function]: shutdown_action_hook()
#7 {main}
  thrown in /var/www/blog/wp-content/plugins/keys-master/includes/system/class-password.php on line 463
```

**Environment (please complete the following information):**
 - PHP version: 8.1.15
 - WordPress version: 6.2
 - Other info: W3TC enabled (not sure if involved)

**Comment by Pierre-Lannoy** [comment]
Hello @stevapple !
OMG! You're definitely right. It will be fixed in the next release… Thanks to catch it 😍

**Comment by Pierre-Lannoy** [comment]
And it's released.
